### ISSUE TITLE
Installation and Usage 

### ISSUE THREAD

**Issue by AdamIshay** [meelgroup/ApproxASP2#1]
Hello, I have read your paper and am interested in using ApproxASP. Are there instructions on installation and usage I can follow to run your code? Thanks!

**Comment by msoos** [comment]
Yes, please read the README, here:

https://github.com/meelgroup/ApproxASP2

It has links for downloading & installation.

Mate

**Comment by mahi045** [comment]
@AdamIshay 
ApproxASP is in branch [approxsmc](https://github.com/meelgroup/ApproxASP2/tree/approxsmc). I added a README in the branch. Hope that it will be helpful.
