### ISSUE TITLE
Independent Support Generation

### ISSUE THREAD

**Issue by AdamIshay** [meelgroup/ApproxASP2#3]
I don’t see independent support files included or a way to generate them. I assume that LP2NORMAL (https://research.ics.aalto.fi/software/asp/lp2normal/)  is used for ASP to SAT translation, and MIS (https://github.com/meelgroup/mis) for independent support generation, whose files can be used with ApproxASP . Is this correct? Thanks.

**Comment by mahi045** [comment]
Hi,
You are correct. We used [arjun](https://arxiv.org/abs/2110.09026) for independent support calculation.
Please note that the independent support file format:
c ind independent support 0
